export const TOGGLE_ADMIN = 'TOGGLE_ADMIN';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SET_CAR_FAMILIES = 'SET_CAR_FAMILIES';

export const GET_CARS = 'GET_CARS';

export const GET_DEALERSHIPS = 'GET_DEALERSHIPS';

export const GET_USER_APPOINTMENTS = 'GET_USER_APPOINTMENTS';
export const POST_USER_APPOINTMENTS = 'POST_USER_APPOINTMENTS';

export const SNACKBAR_ERROR = 'SNACKBAR_ERROR';
export const SNACKBAR_SUCCESS = 'SNACKBAR_SUCCESS';
export const SNACKBAR_CLEAR = 'SNACKBAR_CLEAR';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
export const FORM_LOADING = 'FORM_LOADING';
export const FORM_ERROR = 'FORM_ERROR';
